// <auto-generated />
using System;
using FileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    [Migration("20260819101918_AddProcessingRetryOutboxMessage")]
    partial class AddProcessingRetryOutboxMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Entities.MediaAssetEntity.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("media_assets", "files");

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.MediaProcessing.VideoProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsCriticalError")
                        .HasColumnType("boolean")
                        .HasColumnName("is_critical_error");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_video_processing_status");

                    b.HasIndex("VideoAssetId")
                        .IsUnique()
                        .HasDatabaseName("ux_video_processing_video_asset_id");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("ix_video_processing_status_started_at");

                    b.ToTable("video_processing", "files");
                });

            modelBuilder.Entity("FileService.Domain.Outbox.ProcessingJobOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempted_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("StartedProcessingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_processing_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_processing_job_outbox_messages_media_asset_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_processing_job_outbox_messages_status_next_attempt_at");

                    b.ToTable("processing_job_outbox_messages", (string)null);
                });

            modelBuilder.Entity("FileService.Domain.Outbox.ProcessingRetryOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempted_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedProcessingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_processing_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_processing_retry_outbox_messages_status_next_attempt_at");

                    b.HasIndex("VideoAssetId", "RetryCount")
                        .IsUnique()
                        .HasDatabaseName("UX_processing_retry_outbox_messages_video_asset_id_retry_count");

                    b.ToTable("processing_retry_outbox_messages", (string)null);
                });

            modelBuilder.Entity("FileService.Domain.Entities.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Entities.MediaAssetEntity.MediaAsset");

                    b.HasDiscriminator().HasValue("PREVIEW");
                });

            modelBuilder.Entity("FileService.Domain.Entities.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Entities.MediaAssetEntity.MediaAsset");

                    b.HasDiscriminator().HasValue("VIDEO");
                });

            modelBuilder.Entity("FileService.Domain.Entities.MediaAssetEntity.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.ValueObjects.StorageKey", "FinalKey", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("final_key_bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("final_key_full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("final_key_key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("final_key_prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("final_key_value");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.ValueObjects.StorageKey", "RawKey", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("raw_key_bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("raw_key_full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("raw_key_key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("raw_key_prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("raw_key_value");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.ValueObjects.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId");

                            b1.Property<int>("ExpectedChunksCount");

                            b1.Property<long>("Size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.ToJson("media_data");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.ValueObjects.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Category")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.ValueObjects.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Extension")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.OwnsOne("FileService.Domain.ValueObjects.MediaOwner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("owner_context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_entity_id");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.ValueObjects.StorageReference", "UploadedObject", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("uploaded_object_content_type");

                            b1.Property<string>("ETag")
                                .HasColumnType("text")
                                .HasColumnName("uploaded_object_etag");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("uploaded_object_size_bytes");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.ValueObjects.StorageKey", "Key", b2 =>
                                {
                                    b2.Property<Guid>("StorageReferenceMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Bucket")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("uploaded_object_key_bucket");

                                    b2.Property<string>("FullPath")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("uploaded_object_key_full_path");

                                    b2.Property<string>("Key")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("uploaded_object_key_key");

                                    b2.Property<string>("Prefix")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("uploaded_object_key_prefix");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("uploaded_object_key_value");

                                    b2.HasKey("StorageReferenceMediaAssetId");

                                    b2.ToTable("media_assets", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("StorageReferenceMediaAssetId");
                                });

                            b1.Navigation("Key")
                                .IsRequired();
                        });

                    b.Navigation("FinalKey")
                        .IsRequired();

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("RawKey")
                        .IsRequired();

                    b.Navigation("UploadedObject");
                });

            modelBuilder.Entity("FileService.Domain.MediaProcessing.VideoProcess", b =>
                {
                    b.OwnsMany("FileService.Domain.MediaProcessing.ProcessingStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("text")
                                .HasColumnName("error_message");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<string>("ResultData")
                                .HasColumnType("jsonb")
                                .HasColumnName("result_data");

                            b1.Property<DateTime?>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.Property<string>("StepType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("step_type");

                            b1.Property<Guid>("VideoProcessingId")
                                .HasColumnType("uuid")
                                .HasColumnName("video_processing_id");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer")
                                .HasColumnName("weight");

                            b1.HasKey("Id");

                            b1.HasIndex("Status")
                                .HasDatabaseName("ix_processing_steps_status");

                            b1.HasIndex("StepType")
                                .HasDatabaseName("ix_processing_steps_step_type");

                            b1.HasIndex("VideoProcessingId")
                                .HasDatabaseName("ix_processing_steps_video_processing_id");

                            b1.ToTable("processing_steps", "files");

                            b1.WithOwner()
                                .HasForeignKey("VideoProcessingId");
                        });

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FileService.Domain.Entities.VideoAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.ValueObjects.StorageKey", "HlsRootKey", b1 =>
                        {
                            b1.Property<Guid>("VideoAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_root_key_bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_root_key_full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_root_key_key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_root_key_prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_root_key_value");

                            b1.HasKey("VideoAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("VideoAssetId");
                        });

                    b.OwnsOne("FileService.Domain.ValueObjects.StorageKey", "PreviewKey", b1 =>
                        {
                            b1.Property<Guid>("VideoAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("preview_key_bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("preview_key_full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("preview_key_key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("preview_key_prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("preview_key_value");

                            b1.HasKey("VideoAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("VideoAssetId");
                        });

                    b.OwnsOne("FileService.Domain.ValueObjects.HlsResult", "HlsResult", b1 =>
                        {
                            b1.Property<Guid>("VideoAssetId")
                                .HasColumnType("uuid");

                            b1.HasKey("VideoAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("VideoAssetId");

                            b1.OwnsOne("FileService.Domain.ValueObjects.StorageKey", "ManifestKey", b2 =>
                                {
                                    b2.Property<Guid>("HlsResultVideoAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Bucket")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("hls_result_manifest_key_bucket");

                                    b2.Property<string>("FullPath")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("hls_result_manifest_key_full_path");

                                    b2.Property<string>("Key")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("hls_result_manifest_key_key");

                                    b2.Property<string>("Prefix")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("hls_result_manifest_key_prefix");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("hls_result_manifest_key_value");

                                    b2.HasKey("HlsResultVideoAssetId");

                                    b2.ToTable("media_assets", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("HlsResultVideoAssetId");
                                });

                            b1.Navigation("ManifestKey")
                                .IsRequired();
                        });

                    b.OwnsOne("FileService.Domain.ValueObjects.VideoMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("VideoAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Codec")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("metadata_codec");

                            b1.Property<string>("Container")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("metadata_container");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("interval")
                                .HasColumnName("metadata_duration");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("metadata_height");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("metadata_width");

                            b1.HasKey("VideoAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("VideoAssetId");
                        });

                    b.Navigation("HlsResult")
                        .IsRequired();

                    b.Navigation("HlsRootKey")
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("PreviewKey");
                });
#pragma warning restore 612, 618
        }
    }
}
